schema_version: 2

job:
  name: dgx_serial_benchmark
  output_directory: runs
  continue_on_error: false

experiments:
  - name: imagine_matrix
    config: ../experiments/dgx_smoke3.yaml

  - name: yellow_submarine_iron_man
    config: ../experiments/dgx_smoke4.yaml
