schema_version: 1

job:
  name: mock_two_runs
  output_directory: runs
  continue_on_error: false

execution:
  max_parallel_experiments: 1

experiments:
  - name: mock_first
    config: ../experiments/mock.yaml

  - name: mock_second
    config: ../experimensadts/mock.yaml
