schema_version: 5
job:
  name: mock_two_runs
  output_directory: runs
  continue_on_error: false
experiments:
- name: mock_first
  config: ../experiments/mock.yaml
- name: mock_second
  config: ../experiments/mock.yaml
