schema_version: 5
job:
  name: development_aqueduct_preview
  output_directory: runs
  continue_on_error: true
experiments:
- name: indirect_pg_d32_bb_q25_bi_v4
  config: ../../experiments/final_study/aqueduct/indirect_pg_d32_bb_q25_bi_v4.yaml
  inherit:
    from_job_entry:
      job: local_indirect
      entry: indirect_pg_d32_bb_q25_bi_d32
    stages:
    - image_description
    - verification_prompt
    - verification_image
- name: indirect_pg_d32_bb_g3_bi_v4
  config: ../../experiments/final_study/aqueduct/indirect_pg_d32_bb_g3_bi_v4.yaml
  inherit:
    from_job_entry:
      job: local_indirect
      entry: indirect_pg_d32_bb_g3_bi_d32
    stages:
    - image_description
    - verification_prompt
    - verification_image
- name: indirect_pg_d32_bb_q38_bi_v4
  config: ../../experiments/final_study/aqueduct/indirect_pg_d32_bb_q38_bi_v4.yaml
  inherit:
    from_job_entry:
      job: local_indirect
      entry: indirect_pg_d32_bb_q38_bi_d32
    stages:
    - image_description
    - verification_prompt
    - verification_image
- name: indirect_pg_d32_bb_g4_bi_v4
  config: ../../experiments/final_study/aqueduct/indirect_pg_d32_bb_g4_bi_v4.yaml
  inherit:
    from_job_entry:
      job: local_indirect
      entry: indirect_pg_d32_bb_g4_bi_d32
    stages:
    - image_description
    - verification_prompt
    - verification_image
- name: indirect_pg_o120_bb_q25_bi_v4
  config: ../../experiments/final_study/aqueduct/indirect_pg_o120_bb_q25_bi_v4.yaml
  inherit:
    from_job_entry:
      job: local_indirect
      entry: indirect_pg_o120_bb_q25_bi_d32
    stages:
    - image_description
    - verification_prompt
    - verification_image
- name: indirect_pg_o120_bb_g3_bi_v4
  config: ../../experiments/final_study/aqueduct/indirect_pg_o120_bb_g3_bi_v4.yaml
  inherit:
    from_job_entry:
      job: local_indirect
      entry: indirect_pg_o120_bb_g3_bi_d32
    stages:
    - image_description
    - verification_prompt
    - verification_image
- name: indirect_pg_o120_bb_q38_bi_v4
  config: ../../experiments/final_study/aqueduct/indirect_pg_o120_bb_q38_bi_v4.yaml
  inherit:
    from_job_entry:
      job: local_indirect
      entry: indirect_pg_o120_bb_q38_bi_d32
    stages:
    - image_description
    - verification_prompt
    - verification_image
- name: indirect_pg_o120_bb_g4_bi_v4
  config: ../../experiments/final_study/aqueduct/indirect_pg_o120_bb_g4_bi_v4.yaml
  inherit:
    from_job_entry:
      job: local_indirect
      entry: indirect_pg_o120_bb_g4_bi_d32
    stages:
    - image_description
    - verification_prompt
    - verification_image
- name: indirect_pg_v4_bb_q25_bi_d32
  config: ../../experiments/final_study/development/indirect_pg_v4_bb_q25_bi_d32.yaml
- name: indirect_pg_v4_bb_q25_bi_o120
  config: ../../experiments/final_study/aqueduct/indirect_pg_v4_bb_q25_bi_o120.yaml
  inherit:
    from_entry: indirect_pg_v4_bb_q25_bi_d32
    stages:
    - image_description
    - verification_prompt
    - verification_image
- name: indirect_pg_v4_bb_q25_bi_v4
  config: ../../experiments/final_study/aqueduct/indirect_pg_v4_bb_q25_bi_v4.yaml
  inherit:
    from_entry: indirect_pg_v4_bb_q25_bi_d32
    stages:
    - image_description
    - verification_prompt
    - verification_image
- name: indirect_pg_v4_bb_g3_bi_d32
  config: ../../experiments/final_study/aqueduct/indirect_pg_v4_bb_g3_bi_d32.yaml
  inherit:
    from_entry: indirect_pg_v4_bb_q25_bi_d32
    stages:
    - verification_prompt
    - verification_image
- name: indirect_pg_v4_bb_g3_bi_o120
  config: ../../experiments/final_study/aqueduct/indirect_pg_v4_bb_g3_bi_o120.yaml
  inherit:
    from_entry: indirect_pg_v4_bb_g3_bi_d32
    stages:
    - image_description
    - verification_prompt
    - verification_image
- name: indirect_pg_v4_bb_g3_bi_v4
  config: ../../experiments/final_study/aqueduct/indirect_pg_v4_bb_g3_bi_v4.yaml
  inherit:
    from_entry: indirect_pg_v4_bb_g3_bi_d32
    stages:
    - image_description
    - verification_prompt
    - verification_image
- name: indirect_pg_v4_bb_q38_bi_d32
  config: ../../experiments/final_study/aqueduct/indirect_pg_v4_bb_q38_bi_d32.yaml
  inherit:
    from_entry: indirect_pg_v4_bb_q25_bi_d32
    stages:
    - verification_prompt
    - verification_image
- name: indirect_pg_v4_bb_q38_bi_o120
  config: ../../experiments/final_study/aqueduct/indirect_pg_v4_bb_q38_bi_o120.yaml
  inherit:
    from_entry: indirect_pg_v4_bb_q38_bi_d32
    stages:
    - image_description
    - verification_prompt
    - verification_image
- name: indirect_pg_v4_bb_q38_bi_v4
  config: ../../experiments/final_study/aqueduct/indirect_pg_v4_bb_q38_bi_v4.yaml
  inherit:
    from_entry: indirect_pg_v4_bb_q38_bi_d32
    stages:
    - image_description
    - verification_prompt
    - verification_image
- name: indirect_pg_v4_bb_g4_bi_d32
  config: ../../experiments/final_study/aqueduct/indirect_pg_v4_bb_g4_bi_d32.yaml
  inherit:
    from_entry: indirect_pg_v4_bb_q25_bi_d32
    stages:
    - verification_prompt
    - verification_image
- name: indirect_pg_v4_bb_g4_bi_o120
  config: ../../experiments/final_study/aqueduct/indirect_pg_v4_bb_g4_bi_o120.yaml
  inherit:
    from_entry: indirect_pg_v4_bb_g4_bi_d32
    stages:
    - image_description
    - verification_prompt
    - verification_image
- name: indirect_pg_v4_bb_g4_bi_v4
  config: ../../experiments/final_study/aqueduct/indirect_pg_v4_bb_g4_bi_v4.yaml
  inherit:
    from_entry: indirect_pg_v4_bb_g4_bi_d32
    stages:
    - image_description
    - verification_prompt
    - verification_image
source_jobs:
  local_indirect: {}
